"""
Hiritric - modular tower series, single-file bundle (GENERATED)

Every function of the hiritric package in one file, for upload. Generated by
scripts/bundle_single_file.py from src/hiritric/ and scripts/run_in_rhino.py -
edit those and re-run the bundler, not this file.

Run from inside Rhino (Tools > EditPythonScript / ScriptEditor, "Run File").
Layout: CONFIG, then one section per module (vec, tower, matrix, pattern,
module, wall, color, states, rhino_backend), then the PIPELINE.
"""


# ----------------------------------------------------------------------
#  1. CONFIG
# ----------------------------------------------------------------------
import time
import traceback
from collections import Counter

# QUALITY sets how big a run is. "draft" builds a lighter version of the whole
# series (fewer states, coarser grids, meshes for the louvers) so a first run
# finishes quickly and shows the shape; switch to "final" for the full one.
QUALITY = "draft"
PRESETS = {
    "draft": {"N_STATES": 3, "COLS": 12, "ROWS": 16, "WALL_COLS": 8, "WALL_FLOORS": 10,
              "AS_POLYSURFACE": False},
    "final": {"N_STATES": 5, "COLS": 18, "ROWS": 24, "WALL_COLS": 12, "WALL_FLOORS": 16,
              "AS_POLYSURFACE": True},
}
N_STATES = PRESETS[QUALITY]["N_STATES"]
COLS, ROWS = PRESETS[QUALITY]["COLS"], PRESETS[QUALITY]["ROWS"]   # louver modules around x up the tower
WALL_COLS = PRESETS[QUALITY]["WALL_COLS"]                          # wall units around the tower
WALL_FLOORS = PRESETS[QUALITY]["WALL_FLOORS"]                      # floors = rings of wall units
AS_POLYSURFACE = PRESETS[QUALITY]["AS_POLYSURFACE"]   # louvers as closed lofted polysurfaces; False = meshes, ~10x faster
STATE_SPACING = 90.0        # world units between towers in the row
SEED = 0
GRADIENT = "ember"          # louver modules' color: key into GRADIENTS (color.py)

# The wall: one perforated unit per cell, WALL_FLOORS rings of WALL_COLS units.
# Each unit is a frame with an opening (mattric's perforated unit) cut off by
# the tower body, so it is a closed polysurface whose outer face is a piece of
# the tower surface. Openings widen near attractors (the rule's inset_ratio).
BUILD_WALL_UNITS = True
WALL_FILL = 0.96            # unit size / its cell; < 1 leaves a thin seam between units
WALL_GRADIENT = "slate"     # wall units' color, by attractor influence
SHOW_TOWER_BODY = False     # the body is the units' cutter; shown, it would sit flush with them.
                            #   Kept visible anyway if any wall unit fails, so the shape never has holes.
VIEW_MODE = "Shaded"        # Shaded, Rendered, Ghosted, Arctic, Pen, Artistic, ...
ATTRACTOR_RADIUS = 2.0
ATTRACTOR_COLOR = (255, 255, 255)
TOWER_LAYER_COLOR = (150, 150, 150)

# One state = one dictionary. Numbers and lists of numbers are interpolated
# from START to END; attractors are relative to each tower's own origin.
START = {
    # tower envelope
    "height": 120.0, "floors": 8, "plan_points": 24,
    "radius_x": 20.0, "radius_y": 20.0,
    "squareness": 2.4,          # 2 = ellipse, ~4 = rounded square
    "taper": 1.0, "bulge": 0.0, "twist": 0.0,
    # attractors (x, y, z) relative to the tower origin - just off the facade
    "attractors": [(26.0, 0.0, 25.0), (-8.0, 26.0, 60.0), (0.0, -26.0, 95.0)],
    # field rule
    "falloff": 34.0, "max_tilt": 25.0, "max_depth": 4.0, "void_chance": 0.0,
    # wall units: how far in from the tower surface they reach
    "wall_thickness": 1.2,
}
END = {
    "height": 150.0, "floors": 8, "plan_points": 24,
    "radius_x": 20.0, "radius_y": 20.0,
    "squareness": 4.5,
    "taper": 0.55, "bulge": 0.12, "twist": 100.0,
    "attractors": [(26.0, 0.0, 120.0), (-8.0, 26.0, 70.0), (0.0, -26.0, 30.0)],
    "falloff": 42.0, "max_tilt": 65.0, "max_depth": 9.0, "void_chance": 0.35,
    "wall_thickness": 2.4,
}


# ====================================================================
#  hiritric/vec.py
# ====================================================================

# vec.py
# Tiny 3D vector helpers on plain (x, y, z) tuples - no Rhino, no numpy - so
# matrix/pattern/module logic stays testable outside Rhino and IronPython-
# friendly, same reasoning as the rest of the series.

import math


def add(a, b):
    return (a[0] + b[0], a[1] + b[1], a[2] + b[2])


def sub(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def mul(a, s):
    return (a[0] * s, a[1] * s, a[2] * s)


def dot(a, b):
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def cross(a, b):
    return (a[1] * b[2] - a[2] * b[1],
            a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0])


def length(a):
    return math.sqrt(dot(a, a))


def distance(a, b):
    return length(sub(a, b))


def normalize(a):
    """Unit vector, or (0, 0, 0) if `a` has no length - callers check length()."""
    n = length(a)
    return (0.0, 0.0, 0.0) if n < 1e-12 else mul(a, 1.0 / n)


def lerp(a, b, t):
    return a + (b - a) * t


def rotate_toward(n, target, angle):
    """
    Tilt unit vector `n` by `angle` radians toward `target`, in the plane the
    two span. The result is exactly `angle` away from `n` however `target` is
    scaled - so a tilt limit holds by construction. `n` is returned unchanged
    if `target` is parallel to it.
    """
    tangential = sub(target, mul(n, dot(target, n)))
    if length(tangential) < 1e-9:
        return n
    t = normalize(tangential)
    return normalize(add(mul(n, math.cos(angle)), mul(t, math.sin(angle))))


# ====================================================================
#  hiritric/tower.py
# ====================================================================

# tower.py
# The tower's envelope, as data: one closed floor-plan polygon per control
# floor, which rhino_backend lofts into the NURBS surface the matrix then
# samples. Pure functions - no Rhino.

import math


def floor_plan_points(n_points, radius_x, radius_y, squareness, scale, rotation, z, origin):
    """
    Points of one closed floor plan, a superellipse |x/rx|^n + |y/ry|^n = 1:
    squareness 2 is an ellipse, ~4 a rounded square, larger a squarer one.
    `rotation` in degrees; the first point is not repeated at the end.
    """
    exponent = 2.0 / squareness
    cos_r, sin_r = math.cos(math.radians(rotation)), math.sin(math.radians(rotation))
    points = []
    for k in range(n_points):
        t = 2.0 * math.pi * k / n_points
        c, s = math.cos(t), math.sin(t)
        x = radius_x * scale * math.copysign(abs(c) ** exponent, c)
        y = radius_y * scale * math.copysign(abs(s) ** exponent, s)
        points.append((origin[0] + x * cos_r - y * sin_r,
                       origin[1] + x * sin_r + y * cos_r,
                       origin[2] + z))
    return points


def tower_floor_points(params, origin):
    """
    One plan polygon per control floor, bottom to top. Up the tower the plan
    is scaled (taper toward the top scale, plus a `bulge` fraction at
    mid-height) and rotated (`twist` degrees in total).
    """
    floors = int(params["floors"])
    result = []
    for f in range(floors):
        v = f / (floors - 1)
        scale = 1.0 + (params["taper"] - 1.0) * v + params["bulge"] * math.sin(math.pi * v)
        result.append(floor_plan_points(
            int(params["plan_points"]), params["radius_x"], params["radius_y"],
            params["squareness"], scale, params["twist"] * v, params["height"] * v, origin))
    return result


# ====================================================================
#  hiritric/matrix.py
# ====================================================================

# matrix.py
# The Surface Matrix Dictionary - hiritric's core structure. Same idea as
# mattric's (col, row)-keyed dictionary, but the cells are no longer
# hand-placed grid points: each one is a sample of a NURBS surface in its
# (U, V) parameter space, carrying the surface's own point, normal and
# tangent directions there. The surface is reached only through a
# `sampler(u, v)` callable, so this module stays free of Rhino and directly
# testable with an analytic stand-in.



#  matrix[(col, row)] = {
#      # read off the surface, never changed by the rule
#      "uv", "point", "normal", "u_axis", "v_axis", "cell_w", "cell_h", "seed",
#      # written by the rule
#      "normal_mod", "influence", "depth", "size", "inset_ratio", "taper",
#      "active", "color_t",
#  }
#  `col` runs around the tower (wraps at the seam), `row` climbs it.
def cell_seed(col, row, seed=0):
    """Deterministic pseudo-random value in [0, 1) for a cell - stable across
    runs for the same (col, row, seed), no random.seed()/global state."""
    h = hash((col, row, seed))
    return (h & 0xFFFFFFFF) / 0xFFFFFFFF


def build_matrix(cols, rows, sampler, seed=0):
    """
    Sample a surface into a cols x rows matrix at patch centres
    (u = (col + 0.5) / cols, v = (row + 0.5) / rows), so no sample sits on the
    seam or the top/bottom edge. `sampler(u, v)` returns {"point", "normal",
    "u_axis", "v_axis"} for u, v in 0..1 (section 9's surface_sampler builds
    one from a Rhino surface). U is closed: the last column's neighbour is
    column 0.
    """
    if cols < 2 or rows < 2:
        raise ValueError("need at least 2 columns and 2 rows to measure cell size")

    samples = {}
    for row in range(rows):
        for col in range(cols):
            u, v = (col + 0.5) / cols, (row + 0.5) / rows
            samples[(col, row)] = (u, v, sampler(u, v))

    matrix = {}
    for (col, row), (u, v, s) in samples.items():
        point = s["point"]
        east = samples[((col + 1) % cols, row)][2]["point"]
        north_row = row + 1 if row + 1 < rows else row - 1
        north = samples[(col, north_row)][2]["point"]
        cell_w, cell_h = distance(point, east), distance(point, north)
        matrix[(col, row)] = {
            "uv": (u, v),
            "point": point,
            "normal": s["normal"],
            "u_axis": s["u_axis"],
            "v_axis": s["v_axis"],
            "cell_w": cell_w,
            "cell_h": cell_h,
            "seed": cell_seed(col, row, seed),
            "normal_mod": s["normal"],
            "influence": 0.0,
            "depth": 0.0,
            "size": min(cell_w, cell_h),
            "inset_ratio": 0.25,
            "taper": 1.0,
            "active": True,
            "color_t": 0.0,
        }
    return matrix


# ====================================================================
#  hiritric/pattern.py
# ====================================================================

# pattern.py
# Rules that mutate a surface matrix's rule-driven fields in place - the same
# apply_rule/rule shape as pattric and mattric, but where pattric moved/
# scaled/rotated a 2D square and mattric pushed a point's depth, this rotates
# the surface *normal* toward attractors and sizes a 3D module along it.
# Rules only touch numeric/flag state in each cell dict - never geometry or
# Rhino - so they can be written and checked with plain Python.

import math



def apply_rule(matrix, rule):
    """Apply `rule` to every cell, in (col, row) sorted order for determinism."""
    for key in sorted(matrix.keys()):
        rule(matrix, key, matrix[key])
    return matrix


def falloff(d, falloff_dist):
    """Smoothstep falloff - 1 at d=0, 0 at/after falloff_dist. Same shape as
    skeletric's attractor_radius and pattric/mattric's rules, here against a
    world-space distance instead of a grid distance."""
    t = min(max(d / falloff_dist, 0.0), 1.0)
    return 1.0 - t * t * (3.0 - 2.0 * t)


def attractor_tower_rule(attractors, falloff_dist=35.0, max_tilt=55.0, min_depth=1.0,
                          max_depth=6.0, fill=0.85, inset_far=0.30, inset_near=0.12,
                          taper_far=0.85, taper_near=0.45, void_chance=0.0,
                          void_below=0.25, color_by="influence"):
    """
    The tower's field rule. Every cell blends the pull of all attractors
    (world-space points; nearer ones weigh more via `falloff`) into one
    influence in 0..1 and one pull direction, then sets:

      normal_mod   the surface normal tilted toward the pull by
                   influence * max_tilt degrees - never more than max_tilt,
                   by construction (rotate_toward)
      depth        min_depth -> max_depth with influence
      size         `fill` x the cell's own smaller side, so a module never
                   reaches its neighbours (bounded by construction, like
                   pattric's constrain_to_cell_rule)
      inset_ratio  frame thickness and top narrowing (taper), easing from
      taper        the *_far to the *_near value with influence
      active       a cell far from every attractor (influence < void_below)
                   becomes a void with probability void_chance, drawn from its
                   own seed - a conditional that punches irregular gaps into
                   the calm parts of the facade
      color_t      position along the color gradient: the influence
                   ("influence") or the height up the tower ("height")
    """
    def rule(matrix, key, cell):
        point, normal = cell["point"], cell["normal"]

        total, pull = 0.0, (0.0, 0.0, 0.0)
        for attractor in attractors:
            d = distance(point, attractor)
            w = falloff(d, falloff_dist)
            total += w
            if d > 1e-9:
                pull = add(pull, mul(normalize(sub(attractor, point)), w))
        influence = min(total, 1.0)

        cell["influence"] = influence
        if length(pull) > 1e-9:
            cell["normal_mod"] = rotate_toward(
                normal, normalize(pull), math.radians(max_tilt) * influence)
        else:
            cell["normal_mod"] = normal
        cell["depth"] = lerp(min_depth, max_depth, influence)
        cell["size"] = min(cell["cell_w"], cell["cell_h"]) * fill
        cell["inset_ratio"] = lerp(inset_far, inset_near, influence)
        cell["taper"] = lerp(taper_far, taper_near, influence)
        cell["active"] = not (influence < void_below and cell["seed"] < void_chance)
        cell["color_t"] = cell["uv"][1] if color_by == "height" else influence
    return rule


# ====================================================================
#  hiritric/module.py
# ====================================================================

# module.py
# The tower's module - the one piece of geometry that is designed rather than
# derived: a perforated frustum frame ("louver frame"). Pure function on the
# cell dict, no Rhino: rhino_backend turns the same vertices/faces into
# either a polysurface or a mesh.



#  Seen from the front: a square frame with a square opening (the same
#  outer-square / inset-square idea as mattric's perforated wall units).
#  It is built on the facade's tangent plane and extruded along the
#  attractor-tilted normal, narrowing toward its tip:
#
#            top outer  ____
#                      /_  _\      top ring   (tapered, faces outward)
#          top inner  |  \/  |     inner walls (face into the opening)
#                     |      |     outer walls (face out)
#         base outer  |______|     base ring  (sits on the facade)
#
#  16 vertices in four rings of four, 16 quad faces: a closed solid with one
#  hole through it.
SIGNS = ((-1, -1), (1, -1), (1, 1), (-1, 1))  # counter-clockwise seen from +normal


def module_frame(cell, normal_key="normal_mod"):
    """
    Orthonormal (a, b, n) at the cell: n the cell's normal (the attractor-
    tilted "normal_mod" by default; pass "normal" for the untilted surface
    normal, as the wall units do), a the surface's U tangent made
    perpendicular to n, b = n x a - so a x b = n. Falls back to any
    perpendicular if the tangent ends up parallel to n.
    """
    n = normalize(cell[normal_key])
    u = cell["u_axis"]
    a = normalize(sub(u, mul(n, dot(u, n))))
    if a == (0.0, 0.0, 0.0):
        helper = (1.0, 0.0, 0.0) if abs(n[0]) < 0.9 else (0.0, 1.0, 0.0)
        a = normalize(cross(helper, n))
    return a, cross(n, a), n


def module_mesh(cell):
    """
    (vertices, faces) of the module at `cell`:
      base outer 0-3, base inner 4-7, top outer 8-11, top inner 12-15,
    faces wound so every normal points out of the solid (outer walls out,
    inner walls into the opening, top ring along the tilted normal, base ring
    back into the facade).
    """
    a, b, n = module_frame(cell)
    p = cell["point"]
    half_outer = cell["size"] / 2.0
    half_inner = half_outer - cell["size"] * cell["inset_ratio"]
    tip = add(p, mul(n, cell["depth"]))
    taper = cell["taper"]

    def ring(center, half):
        return [add(center, add(mul(a, sx * half), mul(b, sy * half))) for sx, sy in SIGNS]

    vertices = (ring(p, half_outer) + ring(p, half_inner)
                + ring(tip, half_outer * taper) + ring(tip, half_inner * taper))
    bo, bi, to, ti = 0, 4, 8, 12

    faces = []
    for k in range(4):
        k1 = (k + 1) % 4
        faces.append((bo + k, bo + k1, to + k1, to + k))    # outer wall
        faces.append((bi + k1, bi + k, ti + k, ti + k1))    # inner wall
        faces.append((to + k, to + k1, ti + k1, ti + k))    # top ring
        faces.append((bo + k1, bo + k, bi + k, bi + k1))    # base ring
    return vertices, faces


# ====================================================================
#  hiritric/wall.py
# ====================================================================

# wall.py
# The tower's wall, floor by floor: one perforated unit per cell, ported
# from mattric's perforated wall units. Same construction - an outer box, an
# inner box inset inside it, the second cut out of the first to leave a
# frame with an opening, then the frame's far end cut off by the wall
# surface so its face follows the surface - but oriented on each cell's own
# surface frame (tangent, up, normal) instead of the flat wall's x/y/z, so it
# works on a curved, twisting tower. Row = floor, so each row of cells is one
# floor's ring of units.
#
# This module is pure geometry - the eight corners of each box. Turning them
# into solids, and cutting them by the tower body, is rhino_backend's job.


_SIGNS = ((-1, -1), (1, -1), (1, 1), (-1, 1))  # counter-clockwise seen from +normal


def box_corners(center, a, b, n, half_a, half_b, z0, z1):
    """
    The 8 corners of a box on frame (a, b, n) at `center`: extent +/-half_a
    along a, +/-half_b along b, from z0 to z1 along n. Bottom rectangle first
    (z0), counter-clockwise seen from +n, then the top one (z1) in the same
    order - the order rs.AddBox expects.
    """
    corners = []
    for z in (z0, z1):
        for sa, sb in _SIGNS:
            corners.append(add(center, add(add(mul(a, sa * half_a), mul(b, sb * half_b)),
                                            mul(n, z))))
    return corners


def wall_unit_corners(cell, thickness, fill=0.96):
    """
    (outer, inner) corner lists for the wall unit at `cell`.

    The unit fills the cell's own patch - `fill` of its width around and its
    height up (fill < 1 leaves a thin seam between neighbours) - so a floor's
    units tile its whole ring. It reaches `thickness` in from the surface
    point and out past the surface (by a third of the cell's smaller side,
    enough to clear the surface's curvature over one patch), where the tower
    body cuts it off. The inner box is inset by cell["inset_ratio"] x the
    smaller side all round - the opening - and overshoots the outer box at both
    ends so the subtraction cuts cleanly through.
    """
    a, b, n = module_frame(cell, "normal")
    p = cell["point"]
    half_a = cell["cell_w"] * fill / 2.0
    half_b = cell["cell_h"] * fill / 2.0
    inset = cell["inset_ratio"] * min(cell["cell_w"], cell["cell_h"]) * fill
    reach = min(cell["cell_w"], cell["cell_h"]) / 3.0

    outer = box_corners(p, a, b, n, half_a, half_b, -thickness, reach)
    inner = box_corners(p, a, b, n, half_a - inset, half_b - inset, -thickness - 1.0, reach + 1.0)
    return outer, inner


# ====================================================================
#  hiritric/color.py
# ====================================================================

# color.py
# Color gradients as data: a list of RGB stops, sampled at t in 0..1 by
# linear interpolation between neighbouring stops. Pure - no Rhino.


GRADIENTS = {
    "ember": [(28, 36, 82), (40, 120, 176), (236, 196, 84), (226, 78, 52)],
    "moss":  [(24, 52, 44), (78, 130, 82), (196, 208, 120), (246, 236, 190)],
    "slate": [(30, 34, 44), (96, 108, 128), (190, 198, 210), (250, 250, 250)],
}


def gradient(t, stops):
    """Color at t (clamped to 0..1) along `stops`, evenly spaced, linearly blended."""
    t = min(max(t, 0.0), 1.0)
    if len(stops) == 1:
        return tuple(stops[0])
    scaled = t * (len(stops) - 1)
    i = min(int(scaled), len(stops) - 2)
    f = scaled - i
    lo, hi = stops[i], stops[i + 1]
    return tuple(int(round(lo[c] + (hi[c] - lo[c]) * f)) for c in range(3))


# ====================================================================
#  hiritric/states.py
# ====================================================================

# states.py
# Sequential states: the variation the assignment asks to be shown as a
# series. A state is one parameter dictionary (tower shape + rule settings +
# attractor positions); a sequence is that dictionary interpolated between a
# START and an END over n steps. Pure - no Rhino.


def lerp_value(a, b, t):
    """Interpolate a number, or a (nested) list/tuple of numbers - e.g. a list
    of attractor points. Anything else (a string setting) is not interpolable
    and is taken from the START state."""
    if isinstance(a, (int, float)) and isinstance(b, (int, float)):
        return a + (b - a) * t
    if isinstance(a, (list, tuple)) and isinstance(b, (list, tuple)) and len(a) == len(b):
        return type(a)(lerp_value(x, y, t) for x, y in zip(a, b))
    return a


def interpolate_params(start, end, t):
    """State at position t (0 = start, 1 = end); keys come from `start`."""
    return {key: lerp_value(value, end.get(key, value), t) for key, value in start.items()}


def build_states(start, end, count):
    """`count` states from start to end inclusive."""
    if count < 1:
        raise ValueError("need at least one state")
    if count == 1:
        return [dict(start)]
    return [interpolate_params(start, end, k / (count - 1)) for k in range(count)]


# ====================================================================
#  hiritric/rhino_backend.py
# ====================================================================

# rhino_backend.py
# Rhino adapter for hiritric - the only module that imports
# rhinoscriptsyntax. It lofts the tower, exposes the loft as a plain
# `sampler(u, v)` callable for matrix.py, and draws modules, attractor
# markers and the view. Live-only for this first draft.


try:
    import rhinoscriptsyntax as rs  # only importable from inside Rhino
except ImportError:
    rs = None


def require_rhino():
    if rs is None:
        raise RuntimeError("This function needs to run inside Rhino (rhinoscriptsyntax not found).")


def delete_object(guid):
    """Delete one object from the document."""
    require_rhino()
    rs.DeleteObject(guid)


def ensure_layer(path, color=None):
    """Create a (possibly nested, 'A::B::C') layer path if missing, and set its
    color if given. Same as pattric/mattric's ensure_layer."""
    require_rhino()
    if not rs.IsLayer(path):
        parts = path.split("::")
        current = parts[0]
        if not rs.IsLayer(current):
            rs.AddLayer(current)
        for part in parts[1:]:
            nxt = current + "::" + part
            if not rs.IsLayer(nxt):
                rs.AddLayer(part, parent=current)
            current = nxt
    if color is not None:
        rs.LayerColor(path, color)
    return path


def redraw_off():
    """Stop Rhino redrawing after every object added. Without this each of
    the thousands of objects a run creates forces a viewport redraw, which is
    what makes a big script crawl (or look frozen). Pair with redraw_on()."""
    require_rhino()
    rs.EnableRedraw(False)


def redraw_on():
    """Turn redrawing back on and refresh the viewports once."""
    require_rhino()
    rs.EnableRedraw(True)
    rs.Redraw()


def progress(message, echo=True):
    """Show `message` at Rhino's command prompt (so a long run visibly moves)
    and, if `echo`, print it too."""
    if echo:
        print(message)
    if rs is not None:
        try:
            rs.Prompt(message)
        except Exception:
            pass


def make_floor_curve(points, smooth=True):
    """
    One closed curve through a floor plan's points. With `smooth`, tries the
    smoothest construction first and falls back so a floor never comes back
    empty:
      1. periodic interpolated curve (knotstyle 3) - smooth, no seam kink
      2. interpolated curve through the points plus the first repeated
      3. closed polyline (always works; faceted)
    With smooth=False it goes straight to the polyline. Returns the curve id.
    """
    if smooth:
        for attempt in (lambda: rs.AddInterpCurve(points, 3, 3),
                        lambda: rs.AddInterpCurve(list(points) + [points[0]], 3, 0)):
            curve = attempt()
            if curve and rs.IsCurveClosed(curve):
                return curve
            if curve:
                rs.DeleteObject(curve)
    return rs.AddPolyline(list(points) + [points[0]])


def loft_floors(curves):
    """Loft the floor curves, trying Normal, then Loose, then Straight lofts
    (rs loft_type 0, 1, 2). Returns the list of new surface ids, empty if
    every type fails."""
    for loft_type in (0, 1, 2):
        lofts = rs.AddLoft(curves, loft_type=loft_type)
        if lofts:
            return lofts
    return []


def close_body(body, bottom_curve, top_curve):
    """
    Make the lofted `body` a closed polysurface. Tries Rhino's own
    CapPlanarHoles first; if that leaves it open, caps the planar bottom and
    top floor curves itself and joins them on. Returns the (possibly new) id
    and whether it ended up closed.
    """
    rs.CapPlanarHoles(body)
    if rs.IsPolysurfaceClosed(body):
        return body, True
    caps = (rs.AddPlanarSrf([bottom_curve]) or []) + (rs.AddPlanarSrf([top_curve]) or [])
    joined = rs.JoinSurfaces([body] + caps, delete_input=True) if caps else None
    if joined:
        return joined[0], bool(rs.IsPolysurfaceClosed(joined[0]))
    return body, False


def draw_tower(floor_points, layer, color=None):
    """
    Loft the floor-plan curves (tower_floor_points) into the tower and return
    (body, skin, closed):
      skin    the bare lofted NURBS surface - what the matrix is sampled from
              (a surface, so SurfaceFrame works on it); delete it afterwards
      body    a copy of the skin with its planar top and bottom capped: the
              tower itself, a closed polysurface, on `layer`
      closed  whether the body came out closed (a real solid)
    Falls back rather than giving up: smooth floor curves first, then plain
    polylines; Normal, Loose and Straight loft types (loft_floors); Rhino's
    CapPlanarHoles, then manual planar caps (close_body). Returns
    (None, None, False) only if every loft attempt fails.
    """
    require_rhino()
    ensure_layer(layer, color)
    curves, lofts = [], []
    for smooth in (True, False):
        curves = [make_floor_curve(points, smooth) for points in floor_points]
        lofts = loft_floors(curves) if all(curves) else []
        if lofts:
            break
        rs.DeleteObjects([c for c in curves if c])
    if not lofts:
        return None, None, False
    skin = lofts[0]
    rs.DeleteObjects(lofts[1:])

    body, closed = close_body(rs.CopyObject(skin), curves[0], curves[-1])
    rs.DeleteObjects(curves)
    rs.ObjectLayer(body, layer)
    return body, skin, closed


def surface_sampler(surface_id, center_xy):
    """
    Wrap a Rhino surface as the `sampler(u, v)` build_matrix expects: u, v in
    0..1 are mapped onto the surface's own parameter domains, and the surface
    frame there gives the point, the normal and the U/V tangents. The normal
    is flipped if needed to point away from the tower's axis (`center_xy`),
    since a loft's normal direction depends on curve order.
    """
    require_rhino()
    (u0, u1) = rs.SurfaceDomain(surface_id, 0)
    (v0, v1) = rs.SurfaceDomain(surface_id, 1)

    def sampler(u, v):
        frame = rs.SurfaceFrame(surface_id, (u0 + u * (u1 - u0), v0 + v * (v1 - v0)))
        point = (frame.Origin.X, frame.Origin.Y, frame.Origin.Z)
        normal = (frame.ZAxis.X, frame.ZAxis.Y, frame.ZAxis.Z)
        outward = (point[0] - center_xy[0], point[1] - center_xy[1], 0.0)
        if dot(normal, outward) < 0.0:
            normal = (-normal[0], -normal[1], -normal[2])
        return {
            "point": point,
            "normal": normal,
            "u_axis": (frame.XAxis.X, frame.XAxis.Y, frame.XAxis.Z),
            "v_axis": (frame.YAxis.X, frame.YAxis.Y, frame.YAxis.Z),
        }

    return sampler


def module_polysurface(vertices):
    """
    The module as a closed polysurface, built from lofts: the outer and the
    inner wall are each a straight loft between a base ring and a tip ring
    (four faces apiece), the top and base rings are planar surfaces with the
    opening cut out, and the four are joined. `vertices` is module_mesh's
    (base outer, base inner, top outer, top inner). Returns the id or None.
    """
    rings = [vertices[0:4], vertices[4:8], vertices[8:12], vertices[12:16]]
    base_outer, base_inner, top_outer, top_inner = [
        rs.AddPolyline(list(ring) + [ring[0]]) for ring in rings]

    outer_wall = rs.AddLoft([base_outer, top_outer], loft_type=2) or []
    inner_wall = rs.AddLoft([base_inner, top_inner], loft_type=2) or []
    top_ring = rs.AddPlanarSrf([top_outer, top_inner]) or []
    base_ring = rs.AddPlanarSrf([base_outer, base_inner]) or []
    rs.DeleteObjects([base_outer, base_inner, top_outer, top_inner])

    pieces = [outer_wall, inner_wall, top_ring, base_ring]
    parts = [guid for piece in pieces for guid in piece]
    if not all(pieces):
        rs.DeleteObjects(parts)
        return None
    joined = rs.JoinSurfaces(parts, delete_input=True)
    return joined[0] if joined else None


def draw_module(cell, layer, color=None, as_polysurface=True):
    """
    Draw one module (module_mesh) at `cell`, colored `color`. As a closed
    polysurface built from lofts (module_polysurface) by default; or, with
    `as_polysurface=False`, a single 16-quad mesh - much faster, for quick
    previews with many modules. Returns the new object id, or None.
    """
    require_rhino()
    vertices, faces = module_mesh(cell)
    if as_polysurface:
        guid = module_polysurface(vertices)
    else:
        guid = rs.AddMesh(vertices, faces)
    if guid:
        rs.ObjectLayer(guid, layer)
        if color is not None:
            rs.ObjectColor(guid, color)
    return guid


def draw_wall_unit(outer_corners, inner_corners, body_id, layer, color=None):
    """
    One closed wall unit, the way mattric builds them: a box (`outer_corners`)
    minus a smaller box (`inner_corners`) leaves a frame with an opening, and
    intersecting that frame with the closed tower body keeps only the part
    inside the tower - its outer face becomes a piece of the tower surface,
    so the unit ends exactly where the surface is and comes out a closed
    polysurface. `body_id` is left untouched, ready for the next unit.
    Returns the new object id, or None if a boolean fails.
    """
    require_rhino()
    outer = rs.AddBox(outer_corners)
    inner = rs.AddBox(inner_corners)
    if not (outer and inner):
        rs.DeleteObjects([g for g in (outer, inner) if g])
        return None
    frame = rs.BooleanDifference([outer], [inner], delete_input=True)
    if not frame:
        rs.DeleteObjects([outer, inner])
        return None
    units = rs.BooleanIntersection(frame, [body_id], delete_input=False)
    rs.DeleteObjects(frame)
    if not units:
        return None
    guid = units[0]
    rs.DeleteObjects(units[1:])
    rs.ObjectLayer(guid, layer)
    if color is not None:
        rs.ObjectColor(guid, color)
    return guid


def set_layer_visible(layer, visible):
    """Show or hide a layer - used to keep the tower body as the wall units'
    cutter without displaying it (its surface would sit flush with theirs)."""
    require_rhino()
    rs.LayerVisible(layer, visible)


def draw_attractors(points, radius, layer, color=None):
    """Mark each attractor as a small sphere on its own layer."""
    require_rhino()
    ensure_layer(layer, color)
    ids = []
    for point in points:
        guid = rs.AddSphere(point, radius)
        if guid:
            rs.ObjectLayer(guid, layer)
            ids.append(guid)
    return ids


def set_view(mode="Shaded", zoom=True):
    """Switch the active viewport to a surface display mode (Shaded, Rendered,
    Ghosted, Arctic, Pen, Artistic, ...) - the assignment asks for a view that
    shows surfaces, not wireframe - and optionally zoom to fit."""
    require_rhino()
    try:
        rs.ViewDisplayMode(None, mode)
    except Exception as exc:
        print("Hiritric: could not switch the view to %s (%s) - set it by hand." % (mode, exc))
    if zoom:
        rs.ZoomExtents()


# ----------------------------------------------------------------------
# 10. PIPELINE  - the whole run, top to bottom
# ----------------------------------------------------------------------
def attempt(errors, label, function, *args):
    """
    Run one drawing call; if it raises, count the error under `label`, print
    the first one of each kind, and return None - so a single bad unit or
    module never stops the rest of the run.
    """
    try:
        return function(*args)
    except Exception as exc:
        errors[label] += 1
        if errors[label] == 1:
            print("Hiritric: first %s error - %s: %s" % (label, type(exc).__name__, exc))
        return None


def build_state(index, params, origin, errors):
    """Build and draw one tower state at `origin`. Returns (wall units, modules, voids)."""
    layer = "hiritric::state_%02d" % (index + 1)
    tag = "Hiritric: state %d/%d" % (index + 1, N_STATES)

    # 1. tower: lofted through the floor plans, capped top and bottom into a
    #    closed polysurface; the bare loft surface is kept only to sample from
    progress(tag + " - lofting the tower...", echo=False)
    body, skin, closed = draw_tower(
        tower_floor_points(params, origin), layer + "::tower", TOWER_LAYER_COLOR)
    if skin is None:
        print(tag + " - loft failed with every method, skipped.")
        return 0, 0, 0
    if not closed:
        print(tag + " - tower body is not closed (cap failed); no wall units can be cut.")

    # 2. surface -> two matrix dictionaries, sampled in (U, V): one cell per
    #    wall unit (a floor = a row), one per louver module
    progress(tag + " - sampling the surface...", echo=False)
    sampler = surface_sampler(skin, (origin[0], origin[1]))
    wall_matrix = build_matrix(WALL_COLS, WALL_FLOORS, sampler, seed=SEED)
    matrix = build_matrix(COLS, ROWS, sampler, seed=SEED)
    delete_object(skin)

    # 3. attractor rule on both: the wall matrix takes its opening size
    #    (inset_ratio) and color position from it, the module matrix everything
    attractors = [add(a, origin) for a in params["attractors"]]
    rule = attractor_tower_rule(
        attractors, falloff_dist=params["falloff"], max_tilt=params["max_tilt"],
        max_depth=params["max_depth"], void_chance=params["void_chance"])
    apply_rule(wall_matrix, rule)
    apply_rule(matrix, rule)

    # 4. wall: one closed perforated unit per cell, floor by floor
    walls = 0
    if BUILD_WALL_UNITS and closed:
        wall_stops = GRADIENTS[WALL_GRADIENT]
        for n, key in enumerate(sorted(wall_matrix, key=lambda k: (k[1], k[0])), 1):
            progress("%s - wall unit %d/%d" % (tag, n, len(wall_matrix)), echo=False)
            cell = wall_matrix[key]
            outer, inner = wall_unit_corners(cell, params["wall_thickness"], WALL_FILL)
            unit = attempt(errors, "wall unit", draw_wall_unit, outer, inner, body,
                           layer + "::wall", gradient(cell["color_t"], wall_stops))
            walls += unit is not None
        if walls < len(wall_matrix):
            print("%s - %d of %d wall units failed; leaving the tower body visible instead."
                  % (tag, len(wall_matrix) - walls, len(wall_matrix)))
        elif not SHOW_TOWER_BODY:
            set_layer_visible(layer + "::tower", False)

    # 5. one louver module per active cell, colored along the gradient
    stops = GRADIENTS[GRADIENT]
    drawn = voids = 0
    for n, key in enumerate(sorted(matrix), 1):
        progress("%s - louver module %d/%d" % (tag, n, len(matrix)), echo=False)
        cell = matrix[key]
        if not cell["active"]:
            voids += 1
            continue
        module = attempt(errors, "louver module", draw_module, cell, layer + "::modules",
                         gradient(cell["color_t"], stops), AS_POLYSURFACE)
        drawn += module is not None

    attempt(errors, "attractor marker", draw_attractors, attractors, ATTRACTOR_RADIUS,
            layer + "::attractors", ATTRACTOR_COLOR)
    return walls, drawn, voids


def main():
    started = time.time()
    errors = Counter()
    states = build_states(START, END, N_STATES)
    built = 0
    print("Hiritric: %d states, quality '%s' (%d wall units and %d louver cells per state)."
          % (len(states), QUALITY, WALL_COLS * WALL_FLOORS, COLS * ROWS))

    redraw_off()        # no viewport redraw per object - the difference between seconds and minutes
    try:
        for index, params in enumerate(states):
            origin = (index * STATE_SPACING, 0.0, 0.0)
            try:
                walls, drawn, voids = build_state(index, params, origin, errors)
            except Exception:
                errors["state"] += 1
                print("Hiritric: state %d/%d failed - carrying on with the next one.\n%s"
                      % (index + 1, N_STATES, traceback.format_exc()))
                continue
            built += 1
            print("Hiritric: state %d/%d - %d wall units, %d modules, %d voids "
                  "(twist %.0f deg, taper %.2f)."
                  % (index + 1, N_STATES, walls, drawn, voids, params["twist"], params["taper"]))
    finally:
        redraw_on()     # always hand Rhino its viewports back, even after an error
    set_view(VIEW_MODE)

    summary = ", ".join("%d %s errors" % (count, label) for label, count in sorted(errors.items()))
    print("Hiritric: built %d of %d states in %.0f s%s."
          % (built, N_STATES, time.time() - started, " (" + summary + ")" if summary else ""))


if __name__ == "__main__":
    main()
