"""
Bundle hiritric into ONE file for the assignment upload (code saved as RTF).

The logic lives in src/hiritric/ (edit it there). This script stitches the
configuration from scripts/run_in_rhino.py, every module in src/hiritric/,
and that script's pipeline into a single self-contained file,
outputs/hiritric_single_file.py, with the package imports removed - so every
function is visible in one place. Run it with plain Python (not inside
Rhino):

    python scripts/bundle_single_file.py

The output is generated: re-run this rather than editing it by hand.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src" / "hiritric"
SCRIPT = ROOT / "scripts" / "run_in_rhino.py"
OUT = ROOT / "outputs" / "hiritric_single_file.py"

# dependency order: each module only uses the ones before it
MODULES = ["vec", "tower", "matrix", "pattern", "module", "wall", "color", "states", "rhino_backend"]

BANNER = re.compile(r"^# -{60,}\n#\s*(\d+)\. (.*)\n# -{60,}\n", re.M)
PACKAGE_IMPORT = re.compile(r"^(from \.\w+ import .*|from __future__ import .*)\n", re.M)

HEADER = '''"""
Hiritric - modular tower series, single-file bundle (GENERATED)

Every function of the hiritric package in one file, for upload. Generated by
scripts/bundle_single_file.py from src/hiritric/ and scripts/run_in_rhino.py -
edit those and re-run the bundler, not this file.

Run from inside Rhino (Tools > EditPythonScript / ScriptEditor, "Run File").
Layout: CONFIG, then one section per module (vec, tower, matrix, pattern,
module, wall, color, states, rhino_backend), then the PIPELINE.
"""
'''


def split_script(text):
    """(config section, pipeline section) of scripts/run_in_rhino.py, banners included."""
    marks = list(BANNER.finditer(text))
    sections = {int(m.group(1)): text[m.start():(marks[i + 1].start() if i + 1 < len(marks) else len(text))]
                for i, m in enumerate(marks)}
    return sections[1].rstrip() + "\n", sections[10].rstrip() + "\n"


def module_block(name):
    body = PACKAGE_IMPORT.sub("", (SRC / (name + ".py")).read_text(encoding="utf-8")).strip("\n")
    rule = "# " + "=" * 68
    return "%s\n#  hiritric/%s.py\n%s\n\n%s\n" % (rule, name, rule, body)


def main():
    config, pipeline = split_script(SCRIPT.read_text(encoding="utf-8"))
    parts = [HEADER, config] + [module_block(name) for name in MODULES] + [pipeline]
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n\n".join(parts), encoding="utf-8", newline="\n")
    print("wrote %s (%d lines)" % (OUT.relative_to(ROOT), OUT.read_text(encoding="utf-8").count("\n")))


if __name__ == "__main__":
    main()
